<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WcfEFlatsService" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:ProtectionToken>
              <wsp:Policy>
                <sp:SecureConversationToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                  <wsp:Policy>
                    <sp:RequireDerivedKeys />
                    <sp:BootstrapPolicy>
                      <wsp:Policy>
                        <sp:SignedParts>
                          <sp:Body />
                          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
                        </sp:SignedParts>
                        <sp:EncryptedParts>
                          <sp:Body />
                        </sp:EncryptedParts>
                        <sp:SymmetricBinding>
                          <wsp:Policy>
                            <sp:ProtectionToken>
                              <wsp:Policy>
                                <sp:SpnegoContextToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                                  <wsp:Policy>
                                    <sp:RequireDerivedKeys />
                                  </wsp:Policy>
                                </sp:SpnegoContextToken>
                              </wsp:Policy>
                            </sp:ProtectionToken>
                            <sp:AlgorithmSuite>
                              <wsp:Policy>
                                <sp:Basic256 />
                              </wsp:Policy>
                            </sp:AlgorithmSuite>
                            <sp:Layout>
                              <wsp:Policy>
                                <sp:Strict />
                              </wsp:Policy>
                            </sp:Layout>
                            <sp:IncludeTimestamp />
                            <sp:EncryptSignature />
                            <sp:OnlySignEntireHeadersAndBody />
                          </wsp:Policy>
                        </sp:SymmetricBinding>
                        <sp:Wss11>
                          <wsp:Policy />
                        </sp:Wss11>
                        <sp:Trust10>
                          <wsp:Policy>
                            <sp:MustSupportIssuedTokens />
                            <sp:RequireClientEntropy />
                            <sp:RequireServerEntropy />
                          </wsp:Policy>
                        </sp:Trust10>
                      </wsp:Policy>
                    </sp:BootstrapPolicy>
                  </wsp:Policy>
                </sp:SecureConversationToken>
              </wsp:Policy>
            </sp:ProtectionToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp />
            <sp:EncryptSignature />
            <sp:OnlySignEntireHeadersAndBody />
          </wsp:Policy>
        </sp:SymmetricBinding>
        <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy />
        </sp:Wss11>
        <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportIssuedTokens />
            <sp:RequireClientEntropy />
            <sp:RequireServerEntropy />
          </wsp:Policy>
        </sp:Trust10>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_MessageTestSecured_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_MessageTestSecured_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_MessageTest_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_MessageTest_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_AddStudent_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_AddStudent_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_AddLandlord_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_AddLandlord_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_Login_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_Login_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_Validate_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_Validate_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_AddFlat_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_AddFlat_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_AddToWishlist_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_AddToWishlist_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_RemoveFromWishlist_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_RemoveFromWishlist_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_EditStudentProfile_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_EditStudentProfile_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_EditLandlordProfile_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_EditLandlordProfile_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetUserType_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetUserType_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetStudentData_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetStudentData_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetLandlordData_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetLandlordData_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetAllFlats_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetAllFlats_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetWishlist_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetWishlist_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_SearchFlats_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_SearchFlats_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetFlatsLandlord_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetFlatsLandlord_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_UpdateFlatStatus_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_UpdateFlatStatus_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_UpdateFlat_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_UpdateFlat_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_ConfirmTenants_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_ConfirmTenants_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetConfirmedFlats_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IWcfEFlatsService_GetConfirmedFlats_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="NetTcpBinding_IWcfEFlatsServiceAdmin_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <msb:BinaryEncoding xmlns:msb="http://schemas.microsoft.com/ws/06/2004/mspolicy/netbinary1" />
        <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <msf:WindowsTransportSecurity xmlns:msf="http://schemas.microsoft.com/ws/2006/05/framing/policy">
                  <msf:ProtectionLevel>EncryptAndSign</msf:ProtectionLevel>
                </msf:WindowsTransportSecurity>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
          </wsp:Policy>
        </sp:TransportBinding>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import schemaLocation="http://localhost:8080/?xsd=xsd0" namespace="http://tempuri.org/" />
      <xsd:import schemaLocation="http://localhost:8080/?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import schemaLocation="http://localhost:8080/?xsd=xsd2" namespace="http://schemas.datacontract.org/2004/07/ServerModel" />
      <xsd:import schemaLocation="http://localhost:8080/?xsd=xsd3" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IWcfEFlatsService_MessageTestSecured_InputMessage">
    <wsdl:part name="parameters" element="tns:MessageTestSecured" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_MessageTestSecured_OutputMessage">
    <wsdl:part name="parameters" element="tns:MessageTestSecuredResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_MessageTest_InputMessage">
    <wsdl:part name="parameters" element="tns:MessageTest" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_MessageTest_OutputMessage">
    <wsdl:part name="parameters" element="tns:MessageTestResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_AddStudent_InputMessage">
    <wsdl:part name="parameters" element="tns:AddStudent" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_AddStudent_OutputMessage">
    <wsdl:part name="parameters" element="tns:AddStudentResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_AddLandlord_InputMessage">
    <wsdl:part name="parameters" element="tns:AddLandlord" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_AddLandlord_OutputMessage">
    <wsdl:part name="parameters" element="tns:AddLandlordResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_Login_InputMessage">
    <wsdl:part name="parameters" element="tns:Login" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_Login_OutputMessage">
    <wsdl:part name="parameters" element="tns:LoginResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_Validate_InputMessage">
    <wsdl:part name="parameters" element="tns:Validate" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_Validate_OutputMessage">
    <wsdl:part name="parameters" element="tns:ValidateResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_AddFlat_InputMessage">
    <wsdl:part name="parameters" element="tns:AddFlat" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_AddFlat_OutputMessage">
    <wsdl:part name="parameters" element="tns:AddFlatResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_AddToWishlist_InputMessage">
    <wsdl:part name="parameters" element="tns:AddToWishlist" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_AddToWishlist_OutputMessage">
    <wsdl:part name="parameters" element="tns:AddToWishlistResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_RemoveFromWishlist_InputMessage">
    <wsdl:part name="parameters" element="tns:RemoveFromWishlist" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_RemoveFromWishlist_OutputMessage">
    <wsdl:part name="parameters" element="tns:RemoveFromWishlistResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_EditStudentProfile_InputMessage">
    <wsdl:part name="parameters" element="tns:EditStudentProfile" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_EditStudentProfile_OutputMessage">
    <wsdl:part name="parameters" element="tns:EditStudentProfileResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_EditLandlordProfile_InputMessage">
    <wsdl:part name="parameters" element="tns:EditLandlordProfile" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_EditLandlordProfile_OutputMessage">
    <wsdl:part name="parameters" element="tns:EditLandlordProfileResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetUserType_InputMessage">
    <wsdl:part name="parameters" element="tns:GetUserType" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetUserType_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetUserTypeResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetStudentData_InputMessage">
    <wsdl:part name="parameters" element="tns:GetStudentData" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetStudentData_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetStudentDataResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetLandlordData_InputMessage">
    <wsdl:part name="parameters" element="tns:GetLandlordData" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetLandlordData_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetLandlordDataResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetAllFlats_InputMessage">
    <wsdl:part name="parameters" element="tns:GetAllFlats" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetAllFlats_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetAllFlatsResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetWishlist_InputMessage">
    <wsdl:part name="parameters" element="tns:GetWishlist" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetWishlist_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetWishlistResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_SearchFlats_InputMessage">
    <wsdl:part name="parameters" element="tns:SearchFlats" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_SearchFlats_OutputMessage">
    <wsdl:part name="parameters" element="tns:SearchFlatsResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetFlatsLandlord_InputMessage">
    <wsdl:part name="parameters" element="tns:GetFlatsLandlord" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetFlatsLandlord_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetFlatsLandlordResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_UpdateFlatStatus_InputMessage">
    <wsdl:part name="parameters" element="tns:UpdateFlatStatus" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_UpdateFlatStatus_OutputMessage">
    <wsdl:part name="parameters" element="tns:UpdateFlatStatusResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_UpdateFlat_InputMessage">
    <wsdl:part name="parameters" element="tns:UpdateFlat" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_UpdateFlat_OutputMessage">
    <wsdl:part name="parameters" element="tns:UpdateFlatResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_ConfirmTenants_InputMessage">
    <wsdl:part name="parameters" element="tns:ConfirmTenants" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_ConfirmTenants_OutputMessage">
    <wsdl:part name="parameters" element="tns:ConfirmTenantsResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetConfirmedFlats_InputMessage">
    <wsdl:part name="parameters" element="tns:GetConfirmedFlats" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsService_GetConfirmedFlats_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetConfirmedFlatsResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminLogin_InputMessage">
    <wsdl:part name="parameters" element="tns:AdminLogin" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminLogin_OutputMessage">
    <wsdl:part name="parameters" element="tns:AdminLoginResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminGetTableData_InputMessage">
    <wsdl:part name="parameters" element="tns:AdminGetTableData" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminGetTableData_OutputMessage">
    <wsdl:part name="parameters" element="tns:AdminGetTableDataResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateApplications_InputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateApplications" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateApplications_OutputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateApplicationsResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateFlats_InputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateFlats" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateFlats_OutputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateFlatsResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateStudents_InputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateStudents" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateStudents_OutputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateStudentsResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateLandlords_InputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateLandlords" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateLandlords_OutputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateLandlordsResponse" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateAdmins_InputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateAdmins" />
  </wsdl:message>
  <wsdl:message name="IWcfEFlatsServiceAdmin_AdminUpdateAdmins_OutputMessage">
    <wsdl:part name="parameters" element="tns:AdminUpdateAdminsResponse" />
  </wsdl:message>
  <wsdl:portType name="IWcfEFlatsService">
    <wsdl:operation name="MessageTestSecured">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/MessageTestSecured" message="tns:IWcfEFlatsService_MessageTestSecured_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/MessageTestSecuredResponse" message="tns:IWcfEFlatsService_MessageTestSecured_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="MessageTest">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/MessageTest" message="tns:IWcfEFlatsService_MessageTest_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/MessageTestResponse" message="tns:IWcfEFlatsService_MessageTest_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AddStudent">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/AddStudent" message="tns:IWcfEFlatsService_AddStudent_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/AddStudentResponse" message="tns:IWcfEFlatsService_AddStudent_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AddLandlord">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/AddLandlord" message="tns:IWcfEFlatsService_AddLandlord_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/AddLandlordResponse" message="tns:IWcfEFlatsService_AddLandlord_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="Login">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/Login" message="tns:IWcfEFlatsService_Login_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/LoginResponse" message="tns:IWcfEFlatsService_Login_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="Validate">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/Validate" message="tns:IWcfEFlatsService_Validate_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/ValidateResponse" message="tns:IWcfEFlatsService_Validate_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AddFlat">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/AddFlat" message="tns:IWcfEFlatsService_AddFlat_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/AddFlatResponse" message="tns:IWcfEFlatsService_AddFlat_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AddToWishlist">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/AddToWishlist" message="tns:IWcfEFlatsService_AddToWishlist_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/AddToWishlistResponse" message="tns:IWcfEFlatsService_AddToWishlist_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="RemoveFromWishlist">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/RemoveFromWishlist" message="tns:IWcfEFlatsService_RemoveFromWishlist_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/RemoveFromWishlistResponse" message="tns:IWcfEFlatsService_RemoveFromWishlist_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="EditStudentProfile">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/EditStudentProfile" message="tns:IWcfEFlatsService_EditStudentProfile_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/EditStudentProfileResponse" message="tns:IWcfEFlatsService_EditStudentProfile_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="EditLandlordProfile">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/EditLandlordProfile" message="tns:IWcfEFlatsService_EditLandlordProfile_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/EditLandlordProfileResponse" message="tns:IWcfEFlatsService_EditLandlordProfile_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="GetUserType">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetUserType" message="tns:IWcfEFlatsService_GetUserType_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetUserTypeResponse" message="tns:IWcfEFlatsService_GetUserType_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="GetStudentData">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetStudentData" message="tns:IWcfEFlatsService_GetStudentData_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetStudentDataResponse" message="tns:IWcfEFlatsService_GetStudentData_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="GetLandlordData">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetLandlordData" message="tns:IWcfEFlatsService_GetLandlordData_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetLandlordDataResponse" message="tns:IWcfEFlatsService_GetLandlordData_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="GetAllFlats">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetAllFlats" message="tns:IWcfEFlatsService_GetAllFlats_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetAllFlatsResponse" message="tns:IWcfEFlatsService_GetAllFlats_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="GetWishlist">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetWishlist" message="tns:IWcfEFlatsService_GetWishlist_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetWishlistResponse" message="tns:IWcfEFlatsService_GetWishlist_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="SearchFlats">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/SearchFlats" message="tns:IWcfEFlatsService_SearchFlats_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/SearchFlatsResponse" message="tns:IWcfEFlatsService_SearchFlats_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="GetFlatsLandlord">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetFlatsLandlord" message="tns:IWcfEFlatsService_GetFlatsLandlord_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetFlatsLandlordResponse" message="tns:IWcfEFlatsService_GetFlatsLandlord_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="UpdateFlatStatus">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/UpdateFlatStatus" message="tns:IWcfEFlatsService_UpdateFlatStatus_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/UpdateFlatStatusResponse" message="tns:IWcfEFlatsService_UpdateFlatStatus_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="UpdateFlat">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/UpdateFlat" message="tns:IWcfEFlatsService_UpdateFlat_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/UpdateFlatResponse" message="tns:IWcfEFlatsService_UpdateFlat_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="ConfirmTenants">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/ConfirmTenants" message="tns:IWcfEFlatsService_ConfirmTenants_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/ConfirmTenantsResponse" message="tns:IWcfEFlatsService_ConfirmTenants_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="GetConfirmedFlats">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetConfirmedFlats" message="tns:IWcfEFlatsService_GetConfirmedFlats_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsService/GetConfirmedFlatsResponse" message="tns:IWcfEFlatsService_GetConfirmedFlats_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:portType name="IWcfEFlatsServiceAdmin">
    <wsdl:operation name="AdminLogin">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminLogin" message="tns:IWcfEFlatsServiceAdmin_AdminLogin_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminLoginResponse" message="tns:IWcfEFlatsServiceAdmin_AdminLogin_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AdminGetTableData">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminGetTableData" message="tns:IWcfEFlatsServiceAdmin_AdminGetTableData_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminGetTableDataResponse" message="tns:IWcfEFlatsServiceAdmin_AdminGetTableData_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateApplications">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateApplications" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateApplications_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateApplicationsResponse" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateApplications_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateFlats">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateFlats" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateFlats_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateFlatsResponse" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateFlats_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateStudents">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateStudents" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateStudents_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateStudentsResponse" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateStudents_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateLandlords">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateLandlords" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateLandlords_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateLandlordsResponse" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateLandlords_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateAdmins">
      <wsdl:input wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateAdmins" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateAdmins_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateAdminsResponse" message="tns:IWcfEFlatsServiceAdmin_AdminUpdateAdmins_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WSHttpBinding_IWcfEFlatsService" type="tns:IWcfEFlatsService">
    <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_policy" />
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="MessageTestSecured">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/MessageTestSecured" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_MessageTestSecured_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_MessageTestSecured_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="MessageTest">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/MessageTest" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_MessageTest_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_MessageTest_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddStudent">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/AddStudent" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_AddStudent_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_AddStudent_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddLandlord">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/AddLandlord" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_AddLandlord_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_AddLandlord_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Login">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/Login" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_Login_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_Login_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Validate">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/Validate" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_Validate_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_Validate_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddFlat">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/AddFlat" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_AddFlat_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_AddFlat_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddToWishlist">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/AddToWishlist" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_AddToWishlist_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_AddToWishlist_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RemoveFromWishlist">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/RemoveFromWishlist" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_RemoveFromWishlist_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_RemoveFromWishlist_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="EditStudentProfile">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/EditStudentProfile" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_EditStudentProfile_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_EditStudentProfile_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="EditLandlordProfile">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/EditLandlordProfile" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_EditLandlordProfile_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_EditLandlordProfile_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetUserType">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/GetUserType" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetUserType_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetUserType_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetStudentData">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/GetStudentData" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetStudentData_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetStudentData_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetLandlordData">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/GetLandlordData" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetLandlordData_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetLandlordData_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetAllFlats">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/GetAllFlats" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetAllFlats_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetAllFlats_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetWishlist">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/GetWishlist" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetWishlist_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetWishlist_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SearchFlats">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/SearchFlats" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_SearchFlats_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_SearchFlats_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetFlatsLandlord">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/GetFlatsLandlord" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetFlatsLandlord_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetFlatsLandlord_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateFlatStatus">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/UpdateFlatStatus" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_UpdateFlatStatus_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_UpdateFlatStatus_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateFlat">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/UpdateFlat" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_UpdateFlat_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_UpdateFlat_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ConfirmTenants">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/ConfirmTenants" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_ConfirmTenants_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_ConfirmTenants_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetConfirmedFlats">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsService/GetConfirmedFlats" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetConfirmedFlats_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IWcfEFlatsService_GetConfirmedFlats_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="NetTcpBinding_IWcfEFlatsServiceAdmin" type="tns:IWcfEFlatsServiceAdmin">
    <wsp:PolicyReference URI="#NetTcpBinding_IWcfEFlatsServiceAdmin_policy" />
    <soap12:binding transport="http://schemas.microsoft.com/soap/tcp" />
    <wsdl:operation name="AdminLogin">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminLogin" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AdminGetTableData">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminGetTableData" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateApplications">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateApplications" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateFlats">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateFlats" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateStudents">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateStudents" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateLandlords">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateLandlords" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AdminUpdateAdmins">
      <soap12:operation soapAction="http://tempuri.org/IWcfEFlatsServiceAdmin/AdminUpdateAdmins" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WcfEFlatsService">
    <wsdl:port name="WSHttpBinding_IWcfEFlatsService" binding="tns:WSHttpBinding_IWcfEFlatsService">
      <soap12:address location="http://localhost:8080/WcfEFlatsService" />
      <wsa10:EndpointReference>
        <wsa10:Address>http://localhost:8080/WcfEFlatsService</wsa10:Address>
        <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Upn>teddy_dim27\Klepot</Upn>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
    <wsdl:port name="NetTcpBinding_IWcfEFlatsServiceAdmin" binding="tns:NetTcpBinding_IWcfEFlatsServiceAdmin">
      <soap12:address location="net.tcp://localhost:8090/WcfEFlatsService" />
      <wsa10:EndpointReference>
        <wsa10:Address>net.tcp://localhost:8090/WcfEFlatsService</wsa10:Address>
        <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Upn>teddy_dim27\Klepot</Upn>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>